---

default:
  image: registry.cri.epita.fr/cri/infrastructure/nixpie/nixos-pie
  before_script:
    - echo "Done register"
    - mkdir -p /tmp /var/tmp
    - meson setup -Ddoc=true builddir

stages:
  - build
  - test
  - qa
  - doc

build:
  stage: build
  script:
    - meson compile -C builddir
  artifacts:
    paths:
      - builddir/42sh
    expose_as: 42sh

test:
  stage: test
  dependencies:
    - build
  script:
    - tests/test_ci.sh

clang-format:
  stage: qa
  needs: []
  before_script: []
  script:
    - find . -type f -name '*.[ch]' -exec clang-format --style=file -i {} ';'
    - git diff --exit-code
  after_script:
    - git diff > diff
  artifacts:
    paths:
      - diff
    expose_as: clang-format diff
    when: on_failure

doc:
  stage: doc
  needs: []
  script:
    - meson compile -C builddir doxygen_doc
  artifacts:
    paths:
      - builddir/doxygen_doc
    expose_as: documentation
